
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author moper
 */
public class VentanaDialogo extends javax.swing.JDialog {

    //Req(4;1)
    private boolean returnsAceptar = false;
    
    private javax.swing.DefaultListModel<String> modeloLista;
    
    public static String obvHolder = "Escriba aquí algunas\n" + 
            "observaciones...";
    /**
     * Creates new form VentanaDialogo
     */
    public VentanaDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        modeloLista = new javax.swing.DefaultListModel<>();
        l_Elementos.setModel(modeloLista);
        
        t_Observ.setForeground(Color.GRAY);
        t_Observ.setText(obvHolder);
    }
    

    //Req(4;2)
    public boolean showDialog(java.util.List<String> elementos) 
    { 
        setElementosDonantes(elementos);
        this.setVisible(true);
        return returnsAceptar; 
   } 
   
   //Observer methods 
    public String getObservaciones(){
        return  t_Observ.getText();
    }
    
    private void setElementosDonantes(java.util.List<String> elementos){
        modeloLista.clear();
        for(String e: elementos){
            modeloLista.addElement(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_Elementos = new javax.swing.JPanel();
        t_Titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        e_Elementos = new javax.swing.JLabel();
        l_Elementos = new javax.swing.JList<>();
        b_Aceptar = new javax.swing.JButton();
        b_Cancelar = new javax.swing.JButton();
        t_Observ = new javax.swing.JTextArea();
        e_Observ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resumen de la donacion");
        setMaximumSize(new java.awt.Dimension(370, 307));
        setMinimumSize(new java.awt.Dimension(370, 307));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(370, 307));
        setResizable(false);

        p_Elementos.setBackground(new java.awt.Color(255, 0, 0));

        t_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        t_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        t_Titulo.setText("Elementos Donación");

        javax.swing.GroupLayout p_ElementosLayout = new javax.swing.GroupLayout(p_Elementos);
        p_Elementos.setLayout(p_ElementosLayout);
        p_ElementosLayout.setHorizontalGroup(
            p_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ElementosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(t_Titulo)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        p_ElementosLayout.setVerticalGroup(
            p_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_ElementosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(t_Titulo)
                .addGap(14, 14, 14))
        );

        getContentPane().add(p_Elementos, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(375, 341));

        e_Elementos.setText("Elementos recibidos:");

        l_Elementos.setNextFocusableComponent(t_Observ);

        b_Aceptar.setText("Aceptar");
        b_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AceptarActionPerformed(evt);
            }
        });

        b_Cancelar.setText("Cancelar");
        b_Cancelar.setNextFocusableComponent(b_Cancelar);
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        t_Observ.setColumns(20);
        t_Observ.setRows(5);
        t_Observ.setNextFocusableComponent(b_Aceptar);
        t_Observ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ObservFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_ObservFocusLost(evt);
            }
        });

        e_Observ.setText("Observaciones:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(l_Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(e_Observ))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(t_Observ, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_Cancelar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(e_Elementos)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(e_Observ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_Observ, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_Aceptar)
                            .addComponent(b_Cancelar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(e_Elementos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        // TODO add your handling code here:
        //Req(4;2)
        returnsAceptar = false;
        setVisible(false);
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void b_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AceptarActionPerformed
        // TODO add your handling code here:
        //Req(4;2)
        returnsAceptar = true;
        setVisible(false);
    }//GEN-LAST:event_b_AceptarActionPerformed

    private void t_ObservFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ObservFocusLost
        // TODO add your handling code here:
        if (t_Observ.getText().trim().isEmpty()) {
            // Cambiamos el color de la fuente a gris
            t_Observ.setForeground(Color.GRAY);
            // Volvemos a poner el texto de sugerencia
            t_Observ.setText(obvHolder);
        }
    }//GEN-LAST:event_t_ObservFocusLost

    private void t_ObservFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ObservFocusGained
        // TODO add your handling code here:
        t_Observ.setForeground(Color.BLACK);
        if(t_Observ.getText().equals(obvHolder)){
            t_Observ.setText("");
        }
    }//GEN-LAST:event_t_ObservFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaDialogo dialog = new VentanaDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Aceptar;
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JLabel e_Elementos;
    private javax.swing.JLabel e_Observ;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JList<String> l_Elementos;
    public javax.swing.JPanel p_Elementos;
    public javax.swing.JTextArea t_Observ;
    private javax.swing.JLabel t_Titulo;
    // End of variables declaration//GEN-END:variables

}
