
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author moper
 */
public class VentanaFirma extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public VentanaFirma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        
        firmaPanel = (FirmaPanel) p_Firma;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sp_Derecha = new javax.swing.JPanel();
        b_borrarFirma = new javax.swing.JButton();
        p_Firma = new FirmaPanel();
        b_Confirmar = new javax.swing.JButton();
        sp_Izquierda = new javax.swing.JPanel();
        b_Triangulo = new javax.swing.JButton();
        b_Cuadrado = new javax.swing.JButton();
        b_Circulo = new javax.swing.JButton();
        b_Color = new javax.swing.JButton();
        cb_Rellenar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Firma");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        b_borrarFirma.setText("Rehacer firma");
        b_borrarFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrarFirmaActionPerformed(evt);
            }
        });

        p_Firma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout p_FirmaLayout = new javax.swing.GroupLayout(p_Firma);
        p_Firma.setLayout(p_FirmaLayout);
        p_FirmaLayout.setHorizontalGroup(
            p_FirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_FirmaLayout.setVerticalGroup(
            p_FirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        b_Confirmar.setText("Confirmar firma");
        b_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_DerechaLayout = new javax.swing.GroupLayout(sp_Derecha);
        sp_Derecha.setLayout(sp_DerechaLayout);
        sp_DerechaLayout.setHorizontalGroup(
            sp_DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Firma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sp_DerechaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sp_DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_borrarFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sp_DerechaLayout.setVerticalGroup(
            sp_DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp_DerechaLayout.createSequentialGroup()
                .addComponent(p_Firma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_borrarFirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_Confirmar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(sp_Derecha);

        b_Triangulo.setText("Triángulo");
        b_Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TrianguloActionPerformed(evt);
            }
        });

        b_Cuadrado.setText("Cuadrado");
        b_Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CuadradoActionPerformed(evt);
            }
        });

        b_Circulo.setText("Circulo");
        b_Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CirculoActionPerformed(evt);
            }
        });

        b_Color.setText("Cambiar color");
        b_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ColorActionPerformed(evt);
            }
        });

        cb_Rellenar.setText("Rellenar Figura");
        cb_Rellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_RellenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sp_IzquierdaLayout = new javax.swing.GroupLayout(sp_Izquierda);
        sp_Izquierda.setLayout(sp_IzquierdaLayout);
        sp_IzquierdaLayout.setHorizontalGroup(
            sp_IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_IzquierdaLayout.createSequentialGroup()
                .addGroup(sp_IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_Cuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Triangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Circulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sp_IzquierdaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cb_Rellenar)))
                .addGap(0, 0, 0))
        );
        sp_IzquierdaLayout.setVerticalGroup(
            sp_IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp_IzquierdaLayout.createSequentialGroup()
                .addComponent(b_Cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_Circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cb_Rellenar)
                .addGap(18, 18, 18)
                .addComponent(b_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(sp_Izquierda);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CuadradoActionPerformed
        // TODO add your handling code here:
        firmaPanel.setTool(FirmaPanel.Tool.CUADRADO);
    }//GEN-LAST:event_b_CuadradoActionPerformed

    private void b_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ColorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Selecciona color", firmaPanel.getColorTrazo());
        if (c != null) firmaPanel.setColorTrazo(c);
    }//GEN-LAST:event_b_ColorActionPerformed

    private void b_CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CirculoActionPerformed
        // TODO add your handling code here:
        firmaPanel.setTool(FirmaPanel.Tool.CIRCULO);
    }//GEN-LAST:event_b_CirculoActionPerformed

    private void cb_RellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_RellenarActionPerformed
        // TODO add your handling code here:
        firmaPanel.setRelleno(cb_Rellenar.isSelected());
    }//GEN-LAST:event_cb_RellenarActionPerformed

    private void b_borrarFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrarFirmaActionPerformed
        // TODO add your handling code here:
        firmaPanel.limpiar();
    }//GEN-LAST:event_b_borrarFirmaActionPerformed

    private void b_TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TrianguloActionPerformed
        // TODO add your handling code here:
        firmaPanel.setTool(FirmaPanel.Tool.TRIANGULO);
    }//GEN-LAST:event_b_TrianguloActionPerformed

    private void b_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ConfirmarActionPerformed
        // TODO add your handling code here:
        if(!firmaPanel.hayFirma()){
            JOptionPane.showMessageDialog(null,
                    "Debe realizar una firma antes de continuar",
                    "Error firma", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);
    }//GEN-LAST:event_b_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaFirma dialog = new VentanaFirma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Circulo;
    private javax.swing.JButton b_Color;
    private javax.swing.JButton b_Confirmar;
    private javax.swing.JButton b_Cuadrado;
    private javax.swing.JButton b_Triangulo;
    private javax.swing.JButton b_borrarFirma;
    private javax.swing.JCheckBox cb_Rellenar;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel p_Firma;
    private javax.swing.JPanel sp_Derecha;
    private javax.swing.JPanel sp_Izquierda;
    // End of variables declaration//GEN-END:variables

    public FirmaPanel firmaPanel;
}
