
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author moper
 */
public class VentanaDonantes extends javax.swing.JFrame {

    public javax.swing.DefaultListModel<String> modeloLista;
    
    /**
     * Creates new form VentanaDonantes
     */
    public VentanaDonantes() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Req(2;6)
        modeloLista = new javax.swing.DefaultListModel<>();
        l_ListaDonante.setModel(modeloLista);
          
       
        
    }
    public VentanaDonantes(VentanaPrincipal vp){
        this();
        ventanaPrincipal = vp;
      
         p_Donacion.setBackground(vp.paneles);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t_Entrada = new javax.swing.JTextField();
        l_Info = new javax.swing.JLabel();
        b_Anadir = new javax.swing.JButton();
        l_ListaDinamica = new javax.swing.JScrollPane();
        l_ListaDonante = new javax.swing.JList<>();
        b_Eliminar = new javax.swing.JButton();
        b_Limpiar = new javax.swing.JButton();
        l_Seleccionado = new javax.swing.JLabel();
        l_Contexto = new javax.swing.JLabel();
        t_TipoSangre = new javax.swing.JLabel();
        cb_Sangre = new javax.swing.JComboBox<>();
        b_Cambiar = new javax.swing.JButton();
        b_Confirmar = new javax.swing.JButton();
        p_Donacion = new javax.swing.JPanel();
        l_Nueva = new javax.swing.JLabel();

        setTitle("Nuevo Registro");
        setMaximumSize(new java.awt.Dimension(375, 412));
        setMinimumSize(new java.awt.Dimension(375, 412));
        setPreferredSize(new java.awt.Dimension(375, 412));
        setResizable(false);

        b_Anadir.setText("Añadir elemento");
        b_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AnadirActionPerformed(evt);
            }
        });

        l_ListaDonante.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l_ListaDonanteValueChanged(evt);
            }
        });
        l_ListaDinamica.setViewportView(l_ListaDonante);

        b_Eliminar.setText("Eliminar elemento");
        b_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EliminarActionPerformed(evt);
            }
        });

        b_Limpiar.setText("Limpiar");
        b_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LimpiarActionPerformed(evt);
            }
        });

        l_Seleccionado.setText("Elemento seleccionado:");

        l_Contexto.setText("Escriba aquí que más desea donar:");

        t_TipoSangre.setText("Tipo de sangre: ");

        cb_Sangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        b_Cambiar.setText("Cambiar en registro");
        b_Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CambiarActionPerformed(evt);
            }
        });

        b_Confirmar.setText("Confirmar");
        b_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_TipoSangre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_Cambiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(b_Anadir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_ListaDinamica, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b_Eliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(b_Limpiar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(b_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(l_Seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(l_Contexto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_TipoSangre)
                    .addComponent(cb_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Cambiar))
                .addGap(18, 18, 18)
                .addComponent(l_Contexto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Anadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(l_Seleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(b_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_Limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_Confirmar))
                    .addComponent(l_ListaDinamica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        p_Donacion.setBackground(new java.awt.Color(255, 0, 0));

        l_Nueva.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_Nueva.setForeground(new java.awt.Color(255, 255, 255));
        l_Nueva.setText("Nueva Donación");

        javax.swing.GroupLayout p_DonacionLayout = new javax.swing.GroupLayout(p_Donacion);
        p_Donacion.setLayout(p_DonacionLayout);
        p_DonacionLayout.setHorizontalGroup(
            p_DonacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DonacionLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(l_Nueva)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        p_DonacionLayout.setVerticalGroup(
            p_DonacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_DonacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(l_Nueva)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(p_Donacion, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_ListaDonanteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l_ListaDonanteValueChanged
        // TODO add your handling code here:
        //Req(2;6.b)
        if(!evt.getValueIsAdjusting() && !l_ListaDonante.isSelectionEmpty()){
            String valor = l_ListaDonante.getSelectedValue();
            int indice = l_ListaDonante.getSelectedIndex();
            l_Info.setText("Seleccionado: " + valor + "(" + indice + ")");
        }
    }//GEN-LAST:event_l_ListaDonanteValueChanged

    private void b_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AnadirActionPerformed
        // TODO add your handling code here:
        //Req(2;6.a)
        String nombre = t_Entrada.getText();
        if (!nombre.isEmpty()) {
            modeloLista.addElement(nombre);
            t_Entrada.setText("");
        }
    }//GEN-LAST:event_b_AnadirActionPerformed

    private void b_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EliminarActionPerformed
        // TODO add your handling code here:
        //Req(3;5)
        int Ret=JOptionPane.showConfirmDialog(null, 
        "El elemento seleccionado será eliminado\n" +
        "¿Desea eliminarlo?",
        "Eliminar elemento", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(Ret==JOptionPane.YES_OPTION){
        //Req(2;6.c)
        int indice = l_ListaDonante.getSelectedIndex();
        if( indice != -1){
            modeloLista.remove(indice);
            l_Info.setText("");
        }
        
        JOptionPane.showMessageDialog(null,"El elemento ha sido eliminado",
        "Acción completada",JOptionPane.INFORMATION_MESSAGE);
       }else{
        JOptionPane.showMessageDialog(null,"La acción ha sido cancelada, no se ha eliminado nada",
        "Acción no realizada",JOptionPane.INFORMATION_MESSAGE);
       }
        
    }//GEN-LAST:event_b_EliminarActionPerformed

    private void b_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LimpiarActionPerformed
        // TODO add your handling code here:
        //Req(3;5)
        int Ret=JOptionPane.showConfirmDialog(null, 
        "Se va a eliminar toda la lista\n" +
        "¿Desea eliminarla?",
        "Eliminar lista", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(Ret==JOptionPane.YES_OPTION){
        //Req(2;6.d)
         modeloLista.clear();
         l_Info.setText("");
        
        JOptionPane.showMessageDialog(null,"La lista ha sido eliminada",
        "Acción completada",JOptionPane.INFORMATION_MESSAGE);
       }else{
        JOptionPane.showMessageDialog(null,"La acción ha sido cancelada, no se ha eliminado nada",
        "Acción no realizada",JOptionPane.INFORMATION_MESSAGE);
       }
        
    }//GEN-LAST:event_b_LimpiarActionPerformed

  
    private void b_CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CambiarActionPerformed
        // TODO add your handling code here:
        //Req(3;3)
        String tipo = cb_Sangre.getSelectedItem().toString();
        ventanaPrincipal.setTipoSangre(tipo);
    }//GEN-LAST:event_b_CambiarActionPerformed

    
    private void b_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ConfirmarActionPerformed
        // TODO add your handling code here:
         java.util.List<String> elementos = getElementosParaDonar();
        // Req (3;4)
        ventanaPrincipal.abrirVentanaElementosDonacion(elementos);
    }//GEN-LAST:event_b_ConfirmarActionPerformed

    public void setTipoSangre(String tipo){
        cb_Sangre.setSelectedItem(tipo);
    }
    
    public java.util.List<String> getElementosParaDonar() {
        java.util.List<String> resultado = new java.util.ArrayList<>();
        
        javax.swing.ListModel<String> auxiliar = l_ListaDonante.getModel();
        for (int i = 0; i < auxiliar.getSize(); i++) {
            resultado.add(auxiliar.getElementAt(i));
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDonantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDonantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDonantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDonantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDonantes().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Anadir;
    private javax.swing.JButton b_Cambiar;
    private javax.swing.JButton b_Confirmar;
    private javax.swing.JButton b_Eliminar;
    private javax.swing.JButton b_Limpiar;
    private javax.swing.JComboBox<String> cb_Sangre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_Contexto;
    private javax.swing.JLabel l_Info;
    private javax.swing.JScrollPane l_ListaDinamica;
    private javax.swing.JList<String> l_ListaDonante;
    private javax.swing.JLabel l_Nueva;
    private javax.swing.JLabel l_Seleccionado;
    public javax.swing.JPanel p_Donacion;
    private javax.swing.JTextField t_Entrada;
    private javax.swing.JLabel t_TipoSangre;
    // End of variables declaration//GEN-END:variables

    private VentanaPrincipal ventanaPrincipal;
}
