


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author moper
 */
public class VentanaInicial extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        //Req(3;1)
        this.setVisible(true);
    }

    public VentanaInicial(VentanaPrincipal vp){
        this();
        ventanaPrincipal = vp;
        iniciarCarga();

    }

    private void iniciarCarga(){
        timer = new Timer(100, this);
        timer.start();
    }
    @Override
    public void actionPerformed(java.awt.event.ActionEvent e){
       if(pb_BarraCarga.getValue() < 100){
           pb_BarraCarga.setValue(pb_BarraCarga.getValue() + 10);
       }
       else{
        timer.stop(); 

        timer= new Timer(100, evt -> {
            ventanaPrincipal.setVisible(true);
            this.setVisible(false);
   
        });
        timer.setRepeats(false);
        timer.start();

       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t_Titulo = new javax.swing.JLabel();
        pb_BarraCarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana de carga");
        setMaximumSize(new java.awt.Dimension(369, 164));
        setMinimumSize(new java.awt.Dimension(369, 164));
        setPreferredSize(new java.awt.Dimension(369, 164));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        t_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        t_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        t_Titulo.setText("Bienvenido y recuerde que donar salva");

        pb_BarraCarga.setBackground(new java.awt.Color(255, 255, 255));
        pb_BarraCarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pb_BarraCarga.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pb_BarraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(t_Titulo)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pb_BarraCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar pb_BarraCarga;
    private javax.swing.JLabel t_Titulo;
    // End of variables declaration//GEN-END:variables

    private VentanaPrincipal ventanaPrincipal;
    private javax.swing.Timer timer;
}
