
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author moper
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
public static Color paneles = new Color(255,0,0);  
private static String nombreHolder = "Introduce tu nombre...";
private static String apellidosHolder = "Introduce tus apellidos...";


    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        ventanaDonantes = new VentanaDonantes(this);
        
        ventanaInicial = new VentanaInicial(this);
        //Req(4;1)
        //modal = true para que el dialogo mantenga siempre el foco
        ventanaDialogo = new VentanaDialogo(this, true);
        //Req(4;3)
        ventanaFirma = new VentanaFirma(this, true);
        
        //Para que aparezca al principio 
        t_Nombre.setForeground(Color.GRAY);
        t_Nombre.setText(nombreHolder);
        
        t_Apellidos.setForeground(Color.GRAY);
        t_Apellidos.setText(apellidosHolder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Opciones = new javax.swing.ButtonGroup();
        p_Registro = new javax.swing.JPanel();
        t_Registro = new javax.swing.JLabel();
        tp_Pestañas = new javax.swing.JTabbedPane();
        p_Formulario = new javax.swing.JPanel();
        e_Nombre = new javax.swing.JLabel();
        t_Nombre = new javax.swing.JTextField();
        e_Edad = new javax.swing.JLabel();
        s_Edad = new javax.swing.JSpinner();
        e_Peso = new javax.swing.JLabel();
        s_Peso = new javax.swing.JSpinner();
        e_Sangre = new javax.swing.JLabel();
        cb_Sangre = new javax.swing.JComboBox<>();
        cb_Alergias = new javax.swing.JCheckBox();
        e_Apellidos = new javax.swing.JLabel();
        t_Apellidos = new javax.swing.JTextField();
        b_Confirmar = new javax.swing.JButton();
        b_Firma = new javax.swing.JButton();
        sp_Hospitales = new javax.swing.JSplitPane();
        sp_Derecha = new javax.swing.JScrollPane();
        t_HospitalGeneral = new javax.swing.JTextArea();
        sp_Izquierda = new javax.swing.JScrollPane();
        l_Lugares = new javax.swing.JList<>();
        mb_MenuBar = new javax.swing.JMenuBar();
        m_Archivo = new javax.swing.JMenu();
        mi_NuevoRegistro = new javax.swing.JMenuItem();
        mi_Color = new javax.swing.JMenuItem();
        mi_Guardar = new javax.swing.JMenuItem();
        mi_Salir = new javax.swing.JMenuItem();
        m_TipoDonacion = new javax.swing.JMenu();
        mi_Buscar = new javax.swing.JMenuItem();
        m_Opciones = new javax.swing.JMenu();
        rb_Sangre = new javax.swing.JRadioButtonMenuItem();
        rb_Médula = new javax.swing.JRadioButtonMenuItem();
        rb_Órganos = new javax.swing.JRadioButtonMenuItem();
        m_Ayuda = new javax.swing.JMenu();
        mi_Sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión de Donaciones");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        p_Registro.setBackground(new java.awt.Color(255, 0, 0));

        t_Registro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        t_Registro.setForeground(new java.awt.Color(255, 255, 255));
        t_Registro.setText("Registro Central de Donaciones");

        javax.swing.GroupLayout p_RegistroLayout = new javax.swing.GroupLayout(p_Registro);
        p_Registro.setLayout(p_RegistroLayout);
        p_RegistroLayout.setHorizontalGroup(
            p_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_RegistroLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(t_Registro)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        p_RegistroLayout.setVerticalGroup(
            p_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_RegistroLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(t_Registro)
                .addGap(17, 17, 17))
        );

        getContentPane().add(p_Registro, java.awt.BorderLayout.PAGE_START);

        e_Nombre.setText("Nombre:");

        t_Nombre.setNextFocusableComponent(t_Apellidos);
        t_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_NombreFocusLost(evt);
            }
        });
        t_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_NombreActionPerformed(evt);
            }
        });
        t_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_NombreKeyTyped(evt);
            }
        });

        e_Edad.setText("Edad:");

        s_Edad.setNextFocusableComponent(s_Peso);

        e_Peso.setText("Peso (en kg):");

        s_Peso.setNextFocusableComponent(cb_Sangre);

        e_Sangre.setText("Grupo Sanguíneo:");

        cb_Sangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cb_Sangre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cb_Sangre.setNextFocusableComponent(cb_Alergias);

        cb_Alergias.setText("Alergias");
        cb_Alergias.setNextFocusableComponent(b_Confirmar);
        cb_Alergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_AlergiasActionPerformed(evt);
            }
        });

        e_Apellidos.setText("Apellidos:");

        t_Apellidos.setNextFocusableComponent(s_Edad);
        t_Apellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_ApellidosFocusLost(evt);
            }
        });
        t_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ApellidosActionPerformed(evt);
            }
        });
        t_Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ApellidosKeyTyped(evt);
            }
        });

        b_Confirmar.setText("Confirmar");
        b_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ConfirmarActionPerformed(evt);
            }
        });

        b_Firma.setText("Firma");
        b_Firma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_FormularioLayout = new javax.swing.GroupLayout(p_Formulario);
        p_Formulario.setLayout(p_FormularioLayout);
        p_FormularioLayout.setHorizontalGroup(
            p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_FormularioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_FormularioLayout.createSequentialGroup()
                        .addComponent(e_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cb_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_FormularioLayout.createSequentialGroup()
                        .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_FormularioLayout.createSequentialGroup()
                                .addComponent(e_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_FormularioLayout.createSequentialGroup()
                                .addComponent(e_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_Firma, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_FormularioLayout.createSequentialGroup()
                                .addComponent(e_Apellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_FormularioLayout.createSequentialGroup()
                                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_Alergias)
                                    .addComponent(e_Peso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_FormularioLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(b_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        p_FormularioLayout.setVerticalGroup(
            p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_FormularioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(e_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_Alergias)))
                .addGap(18, 18, 18)
                .addGroup(p_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Firma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Confirmar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tp_Pestañas.addTab("Formulario", p_Formulario);

        t_HospitalGeneral.setEditable(false);
        t_HospitalGeneral.setColumns(20);
        t_HospitalGeneral.setRows(5);
        t_HospitalGeneral.setText("HOSPITAL GENERAL DE ASTURIAS\n---------------------------------------------\nDirección: Avda. de Roma, 26\nTeléfono: 985 08 11 64\n\nHORARIO DE DONACIONES:\nLunes a Viernes: 08:00 - 20:00\nSábados: 09:00 - 14:00\n\nURGENCIAS DE STOCK ACTUALES:\n- Sangre O Negativo (Crítico)\n- Plaquetas (Bajo)");
        sp_Derecha.setViewportView(t_HospitalGeneral);

        sp_Hospitales.setRightComponent(sp_Derecha);

        l_Lugares.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hospital General de Asturias", "Cruz Roja", "Clínica Cristina" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sp_Izquierda.setViewportView(l_Lugares);

        sp_Hospitales.setLeftComponent(sp_Izquierda);

        tp_Pestañas.addTab("Hospitales", sp_Hospitales);

        getContentPane().add(tp_Pestañas, java.awt.BorderLayout.CENTER);

        m_Archivo.setText("Archivo");

        mi_NuevoRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_NuevoRegistro.setText("Nuevo Registro");
        m_Archivo.add(mi_NuevoRegistro);

        mi_Color.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mi_Color.setText("Cambiar color");
        mi_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ColorActionPerformed(evt);
            }
        });
        m_Archivo.add(mi_Color);

        mi_Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_Guardar.setText("Guardar");
        m_Archivo.add(mi_Guardar);

        mi_Salir.setText("Salir");
        m_Archivo.add(mi_Salir);

        mb_MenuBar.add(m_Archivo);

        m_TipoDonacion.setText("Tipo de Donación");

        mi_Buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_Buscar.setText("Buscar");
        mi_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_BuscarActionPerformed(evt);
            }
        });
        m_TipoDonacion.add(mi_Buscar);

        m_Opciones.setText("Opciones");

        bg_Opciones.add(rb_Sangre);
        rb_Sangre.setSelected(true);
        rb_Sangre.setText("Sangre");
        m_Opciones.add(rb_Sangre);

        bg_Opciones.add(rb_Médula);
        rb_Médula.setText("Médula");
        m_Opciones.add(rb_Médula);

        bg_Opciones.add(rb_Órganos);
        rb_Órganos.setText("Órganos");
        m_Opciones.add(rb_Órganos);

        m_TipoDonacion.add(m_Opciones);

        mb_MenuBar.add(m_TipoDonacion);

        m_Ayuda.setText("Ayuda");

        mi_Sobre.setText("Sobre");
        mi_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_SobreActionPerformed(evt);
            }
        });
        m_Ayuda.add(mi_Sobre);

        mb_MenuBar.add(m_Ayuda);

        setJMenuBar(mb_MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ApellidosActionPerformed

    private void cb_AlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_AlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_AlergiasActionPerformed

    private void t_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_NombreActionPerformed

//Req(2;3)
    private void b_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ConfirmarActionPerformed
        // TODO add your handling code here:
        String nombre = t_Nombre.getText();
        String apellidos = t_Apellidos.getText();
        int edad = (int) s_Edad.getValue();
        int peso = (int) s_Peso.getValue();
        
        if(nombre.isEmpty() || apellidos.isEmpty() || edad < 1 || peso < 1 ||
            !ventanaFirma.firmaPanel.hayFirma()){
          JOptionPane.showMessageDialog(null, 
            "Tiene que rellenar todos los datos\n",
            "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Req(2;1)
            if(ventanaDonantes == null){
            ventanaDonantes = new VentanaDonantes();
            }
            //Req(3;1)
            ventanaDonantes.setTipoSangre(getTipoSangre());
            ventanaDonantes.setVisible(true);
        }
    }//GEN-LAST:event_b_ConfirmarActionPerformed

    private void mi_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_SobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_SobreActionPerformed

//req(2;4)
    private void t_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_NombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_t_NombreKeyTyped

    private void t_ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ApellidosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_t_ApellidosKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //Req(3;5)
        int Ret=JOptionPane.showConfirmDialog(null, 
        "¿Quiere cerrar la ventana?\n",
        "Cerrar ventana", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(Ret==JOptionPane.YES_OPTION){
            this.setVisible(false);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mi_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_BuscarActionPerformed
        // TODO add your handling code here:
        //Req(3;5)
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error. \n"
                + "Por favor, inténtelo más tarde.", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_mi_BuscarActionPerformed



    private void t_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_NombreFocusGained
        // TODO add your handling code here:
        t_Nombre.setForeground(Color.BLACK);
        if(t_Nombre.getText().equals(nombreHolder)){
            t_Nombre.setText("");
        }
    }//GEN-LAST:event_t_NombreFocusGained

    private void t_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_NombreFocusLost
        // TODO add your handling code here:
        if (t_Nombre.getText().trim().isEmpty()) {
        // Cambiamos el color de la fuente a gris
        t_Nombre.setForeground(Color.GRAY);
        // Volvemos a poner el texto de sugerencia
        t_Nombre.setText(nombreHolder);
        }
    }//GEN-LAST:event_t_NombreFocusLost

    private void t_ApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ApellidosFocusGained
        // TODO add your handling code here:
        t_Apellidos.setForeground(Color.BLACK);
        if(t_Apellidos.getText().equals(apellidosHolder)){
            t_Apellidos.setText("");
        }
    }//GEN-LAST:event_t_ApellidosFocusGained

    private void t_ApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ApellidosFocusLost
        // TODO add your handling code here:
        if (t_Apellidos.getText().trim().isEmpty()) {
        // Cambiamos el color de la fuente a gris
        t_Apellidos.setForeground(Color.GRAY);
        // Volvemos a poner el texto de sugerencia
        t_Apellidos.setText(apellidosHolder);
        }
    }//GEN-LAST:event_t_ApellidosFocusLost

    private void b_FirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FirmaActionPerformed
        // TODO add your handling code here:
        ventanaFirma.setVisible(true);
    }//GEN-LAST:event_b_FirmaActionPerformed

    private void mi_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ColorActionPerformed
        // TODO add your handling code here:
        //Req(3;6)
        Color mycolor = JColorChooser.showDialog(this, "Seleccione un color de fondo",
                paneles);
        if(mycolor != null){
            paneles = mycolor;
            p_Registro.setBackground(paneles);
             if (ventanaDonantes != null) {
            ventanaDonantes.p_Donacion.setBackground(paneles);
            }
            if (ventanaDialogo != null) {
                ventanaDialogo.p_Elementos.setBackground(paneles);
            }
            
        }
    }//GEN-LAST:event_mi_ColorActionPerformed

    //Req(3;2)
    public void setTipoSangre(String tipo){
        cb_Sangre.setSelectedItem(tipo);
    }
    
    public String getTipoSangre(){
        return cb_Sangre.getSelectedItem().toString();
    }
    
    //Req(4;2) La ventana llamadora procesa el reetorno del dialogo
    public void abrirVentanaElementosDonacion(java.util.List<String> elementos){
        
        boolean ok = ventanaDialogo.showDialog(elementos);
        
        if(ok){
            //Aceptar-> Confirmacion final
 
            int Ret=JOptionPane.showConfirmDialog(null, 
            "¡Registro realizado correctamente!\n"+
              "¿Quiere ver sus observaciones?\n",
                "Confirmación", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(Ret==JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,
                        ventanaDialogo.getObservaciones(),
                        "Observaciones", JOptionPane.PLAIN_MESSAGE);

            }
            else{
            //Cancelar -> Volver a Donantes
            ventanaDonantes.setVisible(true);
            }
           
            ventanaDialogo.t_Observ.setText(VentanaDialogo.obvHolder);
            ventanaDonantes.modeloLista.clear();
            ventanaDonantes.setVisible(false);
            
        } else{
            //Cancelar -> Volver a Donantes
            ventanaDonantes.setVisible(true);
        }
    }
    
    public VentanaDonantes getVentanaDonantes(){
        return ventanaDonantes;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Req(3;1)
                new VentanaPrincipal().setVisible(false);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Confirmar;
    private javax.swing.JButton b_Firma;
    private javax.swing.ButtonGroup bg_Opciones;
    private javax.swing.JCheckBox cb_Alergias;
    private javax.swing.JComboBox<String> cb_Sangre;
    private javax.swing.JLabel e_Apellidos;
    private javax.swing.JLabel e_Edad;
    private javax.swing.JLabel e_Nombre;
    private javax.swing.JLabel e_Peso;
    private javax.swing.JLabel e_Sangre;
    private javax.swing.JList<String> l_Lugares;
    private javax.swing.JMenu m_Archivo;
    private javax.swing.JMenu m_Ayuda;
    private javax.swing.JMenu m_Opciones;
    private javax.swing.JMenu m_TipoDonacion;
    private javax.swing.JMenuBar mb_MenuBar;
    private javax.swing.JMenuItem mi_Buscar;
    private javax.swing.JMenuItem mi_Color;
    private javax.swing.JMenuItem mi_Guardar;
    private javax.swing.JMenuItem mi_NuevoRegistro;
    private javax.swing.JMenuItem mi_Salir;
    private javax.swing.JMenuItem mi_Sobre;
    private javax.swing.JPanel p_Formulario;
    private javax.swing.JPanel p_Registro;
    private javax.swing.JRadioButtonMenuItem rb_Médula;
    private javax.swing.JRadioButtonMenuItem rb_Sangre;
    private javax.swing.JRadioButtonMenuItem rb_Órganos;
    private javax.swing.JSpinner s_Edad;
    private javax.swing.JSpinner s_Peso;
    private javax.swing.JScrollPane sp_Derecha;
    private javax.swing.JSplitPane sp_Hospitales;
    private javax.swing.JScrollPane sp_Izquierda;
    private javax.swing.JTextField t_Apellidos;
    private javax.swing.JTextArea t_HospitalGeneral;
    private javax.swing.JTextField t_Nombre;
    private javax.swing.JLabel t_Registro;
    private javax.swing.JTabbedPane tp_Pestañas;
    // End of variables declaration//GEN-END:variables

    //Req(2;5) l_Lugares
    
    private VentanaDonantes ventanaDonantes;
    private VentanaInicial ventanaInicial;
    //Req(4;1)
    private VentanaDialogo ventanaDialogo;
    //Req(4;3)
    private VentanaFirma ventanaFirma;
}
