
\c universidad

delete from grado_modulo;
delete from estudiante_grado_modulo;
delete from modulo_profesor_aula;
delete from grado;
delete from modulo;
delete from estudiante;
delete from profesor;
delete from departamento;
delete from aula;

insert into grado values (1,'Ingenieria Informatica en Tecnologias de la Informacion', 115);
insert into grado values (2,'Ingenieria en Tecnologias y Servicios de Telecomunicacion', 110);
insert into grado values (3,'Ingenieria Mecanica', 240);
insert into grado values (4,'Ingenieria en Tecnologias Industriales', 145);
insert into grado values (5,'Ingenieria Quimica Industrial', 60);
insert into grado values (6, 'Ingenieria Electronica Industrial y Automatica', 110);
insert into grado values (7, 'Ingenieria Electrica', 80);
insert into grado values (8, 'Ingenieria Nautica y Transporte Maritimo', 35);
insert into grado values (9, 'Ingenieria de Organización Industrial', 60);
insert into grado values (10, 'Marina', 35);


insert into modulo values (1, 'Calculo', 1);
insert into modulo values (2, 'Estadistica', 1);
insert into modulo values (3, 'Algebra Lineal', 1);
insert into modulo values (4, 'Introduccion a Programacion', 1);
insert into modulo values (5, 'Estructuras de Datos', 2);
insert into modulo values (6, 'Ingenieria del Software', 3);
insert into modulo values (7, 'Sistemas de Informacion', 3);
insert into modulo values (8, 'Tecnologias Web', 4);
insert into modulo values (9, 'Algoritmia', 2);
insert into modulo values (10, 'Fundamentos de Informatica', 1);

insert into grado_modulo values (1,1);
insert into grado_modulo values (2,1);
insert into grado_modulo values (3,1);
insert into grado_modulo values (4,1);
insert into grado_modulo values (5,1);
insert into grado_modulo values (6,1);
insert into grado_modulo values (7,1);
insert into grado_modulo values (8,1);
insert into grado_modulo values (9,1);
insert into grado_modulo values (10,1);
insert into grado_modulo values (1,2);
insert into grado_modulo values (2,2);
insert into grado_modulo values (3,2);
insert into grado_modulo values (4,2);
insert into grado_modulo values (5,2);
insert into grado_modulo values (6,2);
insert into grado_modulo values (7,2);
insert into grado_modulo values (8,2);
insert into grado_modulo values (9,2);
insert into grado_modulo values (10,2);
insert into grado_modulo values (1,3);
insert into grado_modulo values (2,3);
insert into grado_modulo values (3,3);
insert into grado_modulo values (4,3);
insert into grado_modulo values (5,3);
insert into grado_modulo values (6,3);
insert into grado_modulo values (7,3);
insert into grado_modulo values (8,3);
insert into grado_modulo values (9,3);
insert into grado_modulo values (10,3);
insert into grado_modulo values (1,4);
insert into grado_modulo values (1,5);
insert into grado_modulo values (1,6);
insert into grado_modulo values (1,7);
insert into grado_modulo values (1,8);
insert into grado_modulo values (1,9);
insert into grado_modulo values (2,10);
insert into grado_modulo values (3,10);
insert into grado_modulo values (4,10);
insert into grado_modulo values (5,10);
insert into grado_modulo values (6,10);
insert into grado_modulo values (7,10);
insert into grado_modulo values (8,10);
insert into grado_modulo values (9,10);
insert into grado_modulo values (10,10);

insert into estudiante values (1, 'Diego', 'Ramos Mendez', false);
insert into estudiante values (2, 'Mercedes', 'Garcia Menendez', false);
insert into estudiante values (3, 'Maria', 'Alvarez Gomez', true);
insert into estudiante values (4, 'Sara', 'Prendes Pardo', true);
insert into estudiante values (5, 'Juan', 'Prieto Vazquez', true);
insert into estudiante values (6, 'Alberto', 'Palacio Gomez', false);
insert into estudiante values (7, 'Pedro', 'Gancedo Alvarez', true);

insert into estudiante_grado_modulo values(1, 1, 1);
insert into estudiante_grado_modulo values(1, 1, 4);
insert into estudiante_grado_modulo values(1, 1, 6);
insert into estudiante_grado_modulo values(1, 1, 7);
insert into estudiante_grado_modulo values(1, 1, 8);
insert into estudiante_grado_modulo values(2, 1, 1);
insert into estudiante_grado_modulo values(2, 1, 6);
insert into estudiante_grado_modulo values(2, 1, 8);
insert into estudiante_grado_modulo values(2, 1, 9);
insert into estudiante_grado_modulo values(3, 1, 1);
insert into estudiante_grado_modulo values(3, 1, 2);
insert into estudiante_grado_modulo values(3, 1, 6);
insert into estudiante_grado_modulo values(3, 1, 7);
insert into estudiante_grado_modulo values(3, 1, 8);
insert into estudiante_grado_modulo values(3, 1, 9);
insert into estudiante_grado_modulo values(4, 1, 1);
insert into estudiante_grado_modulo values(4, 1, 5);
insert into estudiante_grado_modulo values(4, 1, 6);
insert into estudiante_grado_modulo values(4, 1, 9);
insert into estudiante_grado_modulo values(5, 5, 1);
insert into estudiante_grado_modulo values(5, 5, 2);
insert into estudiante_grado_modulo values(6, 5, 1);
insert into estudiante_grado_modulo values(6, 5, 2);
insert into estudiante_grado_modulo values(6, 5, 3);

insert into departamento values(1, 'Ciencias de la Computacion');
insert into departamento values(2, 'Matematicas');
insert into departamento values(3, 'Estadistica');
insert into departamento values(4, 'Telecomunicacion');

insert into profesor values(1, 1, 'Jorge', 'Diez Pelaez');
insert into profesor values(2, 1, 'Pedro', 'Hernandez Arauzo');
insert into profesor values(3, 1, 'Alfredo Santiago', 'Alguero Garcia');
insert into profesor values(4, 1, 'Cristian Augusto', 'Alonso');
insert into profesor values(5, 1, 'Pablo', 'Suarez-Otero Gonzalez');
insert into profesor values(6, 1, 'Pablo Javier', 'Tuya Gonzalez');
insert into profesor values(7, 2, 'Maria Zulima', 'Fernandez Muniz');
insert into profesor values(8, 2, 'Virginia', 'Selgas Buznego');
insert into profesor values(9, 3, 'Hortensia', 'Lopez Garcia');
insert into profesor values(10, 1, 'Maria Jose', 'Suarez Cabal');
insert into profesor values(11, 1, 'Jose', 'Garcia Fanjul');
insert into profesor values(12, 1, 'Maria Teresa', 'Gonzalez Aparicio');
insert into profesor values(13, 2, 'Matias', 'Pico Serrano');

insert into aula values(1, 'AN-A', 60);
insert into aula values(2, 'PL1', 20);
insert into aula values(3, 'PL2', 20);
insert into aula values(4, 'PL3', 30);
insert into aula values(5, 'PL4', 30);
insert into aula values(6, 'DO-9', 50);
insert into aula values(7, 'DE-3', 15);
insert into aula values(8, 'AN-E', 20);
insert into aula values(9, 'AN-B', 60);

insert into modulo_profesor_aula values(2,9,1);
insert into modulo_profesor_aula values(2,9,7);
insert into modulo_profesor_aula values(3,7,1);
insert into modulo_profesor_aula values(3,7,7);
insert into modulo_profesor_aula values(1,8,1);
insert into modulo_profesor_aula values(1,8,7);
insert into modulo_profesor_aula values(8,10,1);
insert into modulo_profesor_aula values(8,10,8);
insert into modulo_profesor_aula values(7,6,1);
insert into modulo_profesor_aula values(7,6,6);
insert into modulo_profesor_aula values(5,2,1);
insert into modulo_profesor_aula values(5,2,2);
insert into modulo_profesor_aula values(5,2,3);
insert into modulo_profesor_aula values(4,1,1);
insert into modulo_profesor_aula values(4,1,4);
insert into modulo_profesor_aula values(6,11,1);
insert into modulo_profesor_aula values(6,11,6);
insert into modulo_profesor_aula values(9,12,1);
insert into modulo_profesor_aula values(9,12,7);
insert into modulo_profesor_aula values(10,3,1);
insert into modulo_profesor_aula values(10,3,2);
insert into modulo_profesor_aula values(10,3,3);
insert into modulo_profesor_aula values(10,3,4);
insert into modulo_profesor_aula values(10,3,5);
insert into modulo_profesor_aula values(10,5,1);
insert into modulo_profesor_aula values(10,5,2);
insert into modulo_profesor_aula values(10,5,3);
insert into modulo_profesor_aula values(10,5,4);
insert into modulo_profesor_aula values(10,5,5);
insert into modulo_profesor_aula values(10,4,1);
insert into modulo_profesor_aula values(10,4,2);
insert into modulo_profesor_aula values(10,4,3);
insert into modulo_profesor_aula values(10,4,4);
insert into modulo_profesor_aula values(10,4,5);



